### ISSUE TITLE
Error while trying to do NPM INSTALL.Help needed

### ISSUE THREAD

**Issue by rssowmiyan** [nrednav/final-year-project#3]
**Operating system used**

-  Windows 10

**Problem**
I have installed all the dependencies correctly.
Can someone please help me to solve this error?
Opened cmd in the client directory and ran NPM INSTALL command. I got this error in the server directory as well.

I have installed Desktop development with C++ via visual studio.But it didn't help.

```
npm ERR! code 1
npm ERR! path C:\Users\thisi\Downloads\final-year-project\client\node_modules\scrypt
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.13.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.4 found at "C:\Users\thisi\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2022
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\thisi\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\thisi\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\thisi\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\thisi\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\thisi\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\thisi\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\thisi\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\thisi\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\thisi\Downloads\final-year-project\client\node_modules\scrypt
npm ERR! gyp ERR! node -v v12.13.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thisi\AppData\Local\npm-cache\_logs\2022-05-15T10_09_11_651Z-debug-0.log
```

**Comment by souravmaji1** [comment]
did you solved this error , i am also getting same error

**Comment by rssowmiyan** [comment]
I couldn't bro😓

**Comment by souravmaji1** [comment]
Ok brother, did you tried installing build tools and after you run npm
install?

**Comment by rssowmiyan** [comment]
Yeah I did

**Comment by souravmaji1** [comment]
Then also didn't worked  ?

**Comment by rssowmiyan** [comment]
Yes
Don't know honestly why it didn't work

**Comment by souravmaji1** [comment]
Yes, basically all the steps have worked smoothly but in this step all the
errors started

**Comment by Zaibali9999** [comment]
Remove package lock json file

**Comment by souravmaji1** [comment]
Did you solved the error

**Comment by souravmaji1** [comment]
brother haven't solved , same error showing

**Comment by souravmaji1** [comment]
brother , now i am able to run 'npm install' in oracles , server folder but not working in client folder

**Comment by souravmaji1** [comment]
hi brother , i was trying and finally i have successfully able to run "npm install " in client,server,oracle folder but now when i type pm2 start in root folder again new error showing

![chota](https://user-images.githubusercontent.com/87080195/170489717-4c9eeaef-cd39-4e38-adc3-c0a8b4fa0c22.PNG)
d

**Comment by souravmaji1** [comment]
hey brother, i have successfully run the command "npm install" but in the
next step doesn't know what it is showing

![zero](https://user-images.githubusercontent.com/87080195/170527231-f18913f3-980c-4e4d-bf27-95130d2a23d4.PNG)

**Comment by souravmaji1** [comment]
hi brother, I have managed to reach uptill this step and i believe that this is the last error and after that i will able to run this application in localhost so can you help me to solve this last error 

![last](https://user-images.githubusercontent.com/87080195/170634337-d58ef38d-564d-4acb-80cd-9697fe159b05.PNG)

**Comment by Zaibali9999** [comment]
its look like a path issuing, please use Ubuntu machine because author
mentioned that he tested on Ubuntu OS
